#!/bin/bash


_python_() {
    python3${pVer%.*} -c "$1"
}

_ANGELBOT_MAIN() {
    $(_python_ 'from git import Repo
import sys
_UPSTREAM_ = "https://github.com/userbottg7/USERBOTY"
_BRANCH_ = "master"
repo = Repo.init()
origin = repo.create_remote("temponame", _UPSTREAM_)
origin.fetch()
repo.create_head(_BRANCH_, origin.refs[_BRANCH_])
repo.heads[_BRANCH_].checkout(True) ')
}

_ANGEL_repo () {
    local hrepo
    hrepo=`echo "aHR0cHM6Ly9naXRodWIuY29tL3VzZXJib3R0ZzcvVVNFUkJPVFkvdXBkYXRl" | base64 -d`
    echo "$rlink"
}

_ANGEL_zip () {
    echo "aHR0cHM6Ly9naXRodWIuY29tL3VzZXJib3R0ZzcvVVNFUkJPVFkvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
}

_ANGELBOT_PLUG() {
    local hrepo=$(_ANGEL_repo)
    $(_python_ 'from git import Repo
import sys
_UPSTREAM_ = "'$hrepo'"
_BRANCH_ = "master"
repo = Repo.init()
origin = repo.create_remote("temponame", _UPSTREAM_)
origin.fetch()
repo.create_head(_BRANCH_, origin.refs[_BRANCH_])
repo.heads[_BRANCH_].checkout(True) ')
}

_starter () {
    local ANGELpath
    ANGELpath="ANGELUserbot.zip"
    echo "••• DOWNLOADING ANGELBOT •••"
    wget -q $(_ANGEL_zip) -O "$ANGELpath"
    ANGELPATH=$(zipinfo -1 "$ANGELpath" | grep -v "/.");
    unzip -qq "$ANGELpath"
    rm -rf "$ANGELpath"
    # _ANGELBOT_MAIN
    cd $ANGELPATH
    # _ANGELBOT_PLUG
    python3 ../setup/updater.py ../requirements.txt requirements.txt
    echo "••• STARTING ANGELBOT •••"
    python3 -m angel
}

_starter
